
test:
	python3 main.py --solver=random
	python3 main.py --solver=sac
	python3 main.py --solver=greedy
	python3 main.py --solver=optimal

train:
	python3 main.py --solver=sac --mode=train --autotune_entropy
